Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'shared_examples']
